import type { DataTableColumn, DataTableRow } from '../components/display/data-table/data-table/data-table.types';

// ── Column definitions ─────────────────────────────────────────────────────

export const PEOPLE_COLUMNS: DataTableColumn[] = [
  { key: 'name',    label: 'Full Name',      width: 180, minWidth: 160 },
  { key: 'email',   label: 'Email Address',  width: 260, minWidth: 200 },
  { key: 'role',    label: 'Role',           width: 120, minWidth: 100 },
  { key: 'tenure',  label: 'Tenure',         width: 100, minWidth: 80  },
  { key: 'awards',  label: 'Awards',         width: 80,  minWidth: 60  },
];

// ── 100-row dataset ────────────────────────────────────────────────────────

export const PEOPLE_100: DataTableRow[] = [
  { name: 'James Wilson',        email: 'james.wilson@veradigm.com',        role: 'Developer',  tenure: '5 years',  awards: '8'  },
  { name: 'Sofia Rodriguez',     email: 'sofia.rodriguez@veradigm.com',     role: 'Designer',   tenure: '3 years',  awards: '12' },
  { name: 'Wei Chen',            email: 'wei.chen@veradigm.com',            role: 'Analyst',    tenure: '7 years',  awards: '15' },
  { name: 'Priya Patel',         email: 'priya.patel@veradigm.com',         role: 'Manager',    tenure: '10 years', awards: '22' },
  { name: 'Kwame Asante',        email: 'kwame.asante@veradigm.com',        role: 'QA',         tenure: '2 years',  awards: '5'  },
  { name: 'Emma Muller',         email: 'emma.muller@veradigm.com',         role: 'Marketing',  tenure: '8 years',  awards: '18' },
  { name: 'Carlos Martinez',     email: 'carlos.martinez@veradigm.com',     role: 'Sales',      tenure: '1 year',   awards: '3'  },
  { name: 'Amara Okafor',        email: 'amara.okafor@veradigm.com',        role: 'Support',    tenure: '4 years',  awards: '9'  },
  { name: 'Michael Davis',       email: 'michael.davis@veradigm.com',       role: 'Developer',  tenure: '6 years',  awards: '11' },
  { name: 'Yuki Tanaka',         email: 'yuki.tanaka@veradigm.com',         role: 'Designer',   tenure: '3 years',  awards: '7'  },
  { name: 'Isabelle Dubois',     email: 'isabelle.dubois@veradigm.com',     role: 'Analyst',    tenure: '9 years',  awards: '20' },
  { name: 'Raj Sharma',          email: 'raj.sharma@veradigm.com',          role: 'Manager',    tenure: '12 years', awards: '25' },
  { name: 'Fatima Al-Rashid',    email: 'fatima.alrashid@veradigm.com',     role: 'QA',         tenure: '1 year',   awards: '2'  },
  { name: 'Ivan Petrov',         email: 'ivan.petrov@veradigm.com',         role: 'Marketing',  tenure: '5 years',  awards: '10' },
  { name: 'Alejandro Hernandez', email: 'alejandro.hernandez@veradigm.com', role: 'Sales',      tenure: '2 years',  awards: '4'  },
  { name: 'Nia Adeyemi',         email: 'nia.adeyemi@veradigm.com',         role: 'Support',    tenure: '6 years',  awards: '14' },
  { name: 'Sarah Johnson',       email: 'sarah.johnson@veradigm.com',       role: 'Developer',  tenure: '4 years',  awards: '8'  },
  { name: 'Kenji Nakamura',      email: 'kenji.nakamura@veradigm.com',      role: 'Designer',   tenure: '8 years',  awards: '16' },
  { name: 'Emily Brown',         email: 'emily.brown@veradigm.com',         role: 'Analyst',    tenure: '3 years',  awards: '6'  },
  { name: 'Omar Hassan',         email: 'omar.hassan@veradigm.com',         role: 'Manager',    tenure: '11 years', awards: '24' },
  { name: 'Divya Nair',          email: 'divya.nair@veradigm.com',          role: 'QA',         tenure: '4 years',  awards: '9'  },
  { name: 'Pierre Lefebvre',     email: 'pierre.lefebvre@veradigm.com',     role: 'Marketing',  tenure: '7 years',  awards: '17' },
  { name: 'Jessica Garcia',      email: 'jessica.garcia@veradigm.com',      role: 'Sales',      tenure: '3 years',  awards: '7'  },
  { name: 'Chidi Nwosu',         email: 'chidi.nwosu@veradigm.com',         role: 'Support',    tenure: '2 years',  awards: '4'  },
  { name: 'Robert Thompson',     email: 'robert.thompson@veradigm.com',     role: 'Developer',  tenure: '9 years',  awards: '19' },
  { name: 'Mei Lin',             email: 'mei.lin@veradigm.com',             role: 'Designer',   tenure: '5 years',  awards: '11' },
  { name: 'Valentina Cruz',      email: 'valentina.cruz@veradigm.com',      role: 'Analyst',    tenure: '6 years',  awards: '13' },
  { name: 'Arjun Gupta',         email: 'arjun.gupta@veradigm.com',         role: 'Manager',    tenure: '8 years',  awards: '21' },
  { name: 'Zara Ibrahim',        email: 'zara.ibrahim@veradigm.com',        role: 'QA',         tenure: '3 years',  awards: '6'  },
  { name: 'Sven Johansson',      email: 'sven.johansson@veradigm.com',      role: 'Marketing',  tenure: '4 years',  awards: '8'  },
  { name: 'Ricardo Morales',     email: 'ricardo.morales@veradigm.com',     role: 'Sales',      tenure: '7 years',  awards: '15' },
  { name: 'Yewande Seun',        email: 'yewande.seun@veradigm.com',        role: 'Support',    tenure: '5 years',  awards: '12' },
  { name: 'William Anderson',    email: 'william.anderson@veradigm.com',    role: 'Developer',  tenure: '10 years', awards: '23' },
  { name: 'Hiroshi Yamamoto',    email: 'hiroshi.yamamoto@veradigm.com',    role: 'Designer',   tenure: '6 years',  awards: '14' },
  { name: 'Nicole Williams',     email: 'nicole.williams@veradigm.com',     role: 'Analyst',    tenure: '2 years',  awards: '5'  },
  { name: 'Aditya Kumar',        email: 'aditya.kumar@veradigm.com',        role: 'Manager',    tenure: '13 years', awards: '26' },
  { name: 'Layla Al-Farsi',      email: 'layla.alfarsi@veradigm.com',       role: 'QA',         tenure: '1 year',   awards: '2'  },
  { name: 'Katarzyna Kowalska',  email: 'katarzyna.kowalska@veradigm.com',  role: 'Marketing',  tenure: '9 years',  awards: '20' },
  { name: 'Jose Perez',          email: 'jose.perez@veradigm.com',          role: 'Sales',      tenure: '4 years',  awards: '9'  },
  { name: 'Kofi Mensah',         email: 'kofi.mensah@veradigm.com',         role: 'Support',    tenure: '3 years',  awards: '6'  },
  { name: 'Jennifer Taylor',     email: 'jennifer.taylor@veradigm.com',     role: 'Developer',  tenure: '5 years',  awards: '11' },
  { name: 'Sakura Watanabe',     email: 'sakura.watanabe@veradigm.com',     role: 'Designer',   tenure: '7 years',  awards: '16' },
  { name: 'David Okonkwo',       email: 'david.okonkwo@veradigm.com',       role: 'Analyst',    tenure: '4 years',  awards: '8'  },
  { name: 'Neha Singh',          email: 'neha.singh@veradigm.com',          role: 'Manager',    tenure: '6 years',  awards: '15' },
  { name: 'Emeka Diallo',        email: 'emeka.diallo@veradigm.com',        role: 'QA',         tenure: '5 years',  awards: '10' },
  { name: 'Luca Rossi',          email: 'luca.rossi@veradigm.com',          role: 'Marketing',  tenure: '3 years',  awards: '7'  },
  { name: 'Ashley Miller',       email: 'ashley.miller@veradigm.com',       role: 'Sales',      tenure: '8 years',  awards: '18' },
  { name: 'Sunita Rao',          email: 'sunita.rao@veradigm.com',          role: 'Support',    tenure: '2 years',  awards: '4'  },
  { name: 'Daniel Jackson',      email: 'daniel.jackson@veradigm.com',      role: 'Developer',  tenure: '11 years', awards: '22' },
  { name: 'Min-Ji Park',         email: 'minji.park@veradigm.com',          role: 'Designer',   tenure: '4 years',  awards: '9'  },
  { name: 'Amanda Thomas',       email: 'amanda.thomas@veradigm.com',       role: 'Analyst',    tenure: '7 years',  awards: '14' },
  { name: 'Hassan Khalil',       email: 'hassan.khalil@veradigm.com',       role: 'Manager',    tenure: '15 years', awards: '30' },
  { name: 'Ananya Bose',         email: 'ananya.bose@veradigm.com',         role: 'QA',         tenure: '6 years',  awards: '12' },
  { name: 'Ingrid Nielsen',      email: 'ingrid.nielsen@veradigm.com',      role: 'Marketing',  tenure: '5 years',  awards: '11' },
  { name: 'Miguel Sanchez',      email: 'miguel.sanchez@veradigm.com',      role: 'Sales',      tenure: '3 years',  awards: '7'  },
  { name: 'Adaeze Eze',          email: 'adaeze.eze@veradigm.com',          role: 'Support',    tenure: '4 years',  awards: '8'  },
  { name: 'Christopher Harris',  email: 'christopher.harris@veradigm.com',  role: 'Developer',  tenure: '8 years',  awards: '17' },
  { name: 'Jae-Won Lee',         email: 'jaewon.lee@veradigm.com',          role: 'Designer',   tenure: '2 years',  awards: '5'  },
  { name: 'Gabriela Flores',     email: 'gabriela.flores@veradigm.com',     role: 'Analyst',    tenure: '9 years',  awards: '19' },
  { name: 'Vikram Mehta',        email: 'vikram.mehta@veradigm.com',        role: 'Manager',    tenure: '7 years',  awards: '16' },
  { name: 'Nour Khalid',         email: 'nour.khalid@veradigm.com',         role: 'QA',         tenure: '3 years',  awards: '6'  },
  { name: 'Zofia Wisniewska',    email: 'zofia.wisniewska@veradigm.com',    role: 'Marketing',  tenure: '6 years',  awards: '13' },
  { name: 'Alejandra Vega',      email: 'alejandra.vega@veradigm.com',      role: 'Sales',      tenure: '1 year',   awards: '3'  },
  { name: 'Seun Afolabi',        email: 'seun.afolabi@veradigm.com',        role: 'Support',    tenure: '5 years',  awards: '10' },
  { name: 'Matthew White',       email: 'matthew.white@veradigm.com',       role: 'Developer',  tenure: '4 years',  awards: '9'  },
  { name: 'Xiaofei Zhang',       email: 'xiaofei.zhang@veradigm.com',       role: 'Designer',   tenure: '10 years', awards: '21' },
  { name: 'Maria Lopez',         email: 'maria.lopez@veradigm.com',         role: 'Analyst',    tenure: '3 years',  awards: '7'  },
  { name: 'Rohan Joshi',         email: 'rohan.joshi@veradigm.com',         role: 'Manager',    tenure: '9 years',  awards: '20' },
  { name: 'Youssef Mahmoud',     email: 'youssef.mahmoud@veradigm.com',     role: 'QA',         tenure: '2 years',  awards: '4'  },
  { name: 'Olga Ivanova',        email: 'olga.ivanova@veradigm.com',        role: 'Marketing',  tenure: '7 years',  awards: '15' },
  { name: 'Benjamin Scott',      email: 'benjamin.scott@veradigm.com',      role: 'Sales',      tenure: '6 years',  awards: '13' },
  { name: 'Rania Saleh',         email: 'rania.saleh@veradigm.com',         role: 'Support',    tenure: '4 years',  awards: '8'  },
  { name: 'Jennifer Lewis',      email: 'jennifer.lewis@veradigm.com',      role: 'Developer',  tenure: '5 years',  awards: '11' },
  { name: 'Takeshi Ito',         email: 'takeshi.ito@veradigm.com',         role: 'Designer',   tenure: '3 years',  awards: '7'  },
  { name: 'Isabella Gonzalez',   email: 'isabella.gonzalez@veradigm.com',   role: 'Analyst',    tenure: '8 years',  awards: '17' },
  { name: 'Dmitri Volkov',       email: 'dmitri.volkov@veradigm.com',       role: 'Manager',    tenure: '14 years', awards: '28' },
  { name: 'Yasmin Rashid',       email: 'yasmin.rashid@veradigm.com',       role: 'QA',         tenure: '1 year',   awards: '2'  },
  { name: 'Bjorn Eriksson',      email: 'bjorn.eriksson@veradigm.com',      role: 'Marketing',  tenure: '5 years',  awards: '10' },
  { name: 'Patricia Ramirez',    email: 'patricia.ramirez@veradigm.com',    role: 'Sales',      tenure: '7 years',  awards: '15' },
  { name: 'Chisom Ike',          email: 'chisom.ike@veradigm.com',          role: 'Support',    tenure: '3 years',  awards: '6'  },
  { name: 'Nathan Clark',        email: 'nathan.clark@veradigm.com',        role: 'Developer',  tenure: '6 years',  awards: '12' },
  { name: 'Haruki Kobayashi',    email: 'haruki.kobayashi@veradigm.com',    role: 'Designer',   tenure: '4 years',  awards: '9'  },
  { name: 'Elena Vasquez',       email: 'elena.vasquez@veradigm.com',       role: 'Analyst',    tenure: '5 years',  awards: '11' },
  { name: 'Leila Hosseini',      email: 'leila.hosseini@veradigm.com',      role: 'Manager',    tenure: '11 years', awards: '23' },
  { name: 'Obinna Obi',          email: 'obinna.obi@veradigm.com',          role: 'QA',         tenure: '2 years',  awards: '4'  },
  { name: 'Camille Fontaine',    email: 'camille.fontaine@veradigm.com',    role: 'Marketing',  tenure: '8 years',  awards: '17' },
  { name: 'Luis Castillo',       email: 'luis.castillo@veradigm.com',       role: 'Sales',      tenure: '4 years',  awards: '8'  },
  { name: 'Adeola Ogundimu',     email: 'adeola.ogundimu@veradigm.com',     role: 'Support',    tenure: '6 years',  awards: '12' },
  { name: 'Anthony Robinson',    email: 'anthony.robinson@veradigm.com',    role: 'Developer',  tenure: '7 years',  awards: '14' },
  { name: 'Yuna Kim',            email: 'yuna.kim@veradigm.com',            role: 'Designer',   tenure: '5 years',  awards: '10' },
  { name: 'Claudia Herrera',     email: 'claudia.herrera@veradigm.com',     role: 'Analyst',    tenure: '3 years',  awards: '6'  },
  { name: 'Vikrant Pillai',      email: 'vikrant.pillai@veradigm.com',      role: 'Manager',    tenure: '10 years', awards: '21' },
  { name: 'Tariq Haddad',        email: 'tariq.haddad@veradigm.com',        role: 'QA',         tenure: '4 years',  awards: '8'  },
  { name: 'Sigrid Andersen',     email: 'sigrid.andersen@veradigm.com',     role: 'Marketing',  tenure: '6 years',  awards: '13' },
  { name: 'Gabriel Silva',       email: 'gabriel.silva@veradigm.com',       role: 'Sales',      tenure: '2 years',  awards: '5'  },
  { name: 'Chiamaka Onyeka',     email: 'chiamaka.onyeka@veradigm.com',     role: 'Support',    tenure: '7 years',  awards: '14' },
  { name: 'Kevin Walker',        email: 'kevin.walker@veradigm.com',        role: 'Developer',  tenure: '12 years', awards: '24' },
  { name: 'Ami Sato',            email: 'ami.sato@veradigm.com',            role: 'Designer',   tenure: '3 years',  awards: '7'  },
  { name: 'Rosa Jimenez',        email: 'rosa.jimenez@veradigm.com',        role: 'Analyst',    tenure: '8 years',  awards: '16' },
  { name: 'Nikhil Iyer',         email: 'nikhil.iyer@veradigm.com',         role: 'Manager',    tenure: '5 years',  awards: '11' },
];

// ── Subsets for "With Checkboxes" tab ─────────────────────────────────────

export const PEOPLE_CHECKBOXES_A: DataTableRow[] = PEOPLE_100.slice(0, 50);
export const PEOPLE_CHECKBOXES_B: DataTableRow[] = PEOPLE_100.slice(50);
